//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GtreasuryAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class tblLoan
    {
        public int intLoanId { get; set; }
        public Nullable<double> dblLoanAmont { get; set; }
        public Nullable<System.DateTime> dtmLoanStartDate { get; set; }
        public Nullable<int> intLoanTerm { get; set; }
        public Nullable<int> dblLoadFixedRate { get; set; }
        public int intClientId { get; set; }
    
        public virtual tblClient tblClient { get; set; }


        [NotMapped]
        public string strClientName { get; set; }

    }
}
